apiVersion: v1
kind: Service
metadata:
  name: member-registration
  namespace: default
  labels:
    app: member-registration
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: member-registration
  type: ClusterIP
