apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml


patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: helm-controller
    namespace: flux-system
  spec:
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kustomize-controller
    namespace: flux-system
  spec:
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: image-automation-controller
    namespace: flux-system
  spec:
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: image-reflector-controller
    namespace: flux-system
  spec:
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: notification-controller
    namespace: flux-system
  spec:
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: source-controller
    namespace: flux-system
  spec:
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
