apiVersion: apps/v1
kind: Deployment
metadata:
  name: mand
  namespace: default
  labels:
    app: mand
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mand
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      name: mand
      labels:
        app: mand
    spec:
      containers:
      - name: mand
        image: ghcr.io/wisvch/mand:20220117-5205c76
        imagePullPolicy: IfNotPresent
        env:
        - name: DBCONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: mand
              key: DB_CONNSTRING
        - name: CONNECTURL
          value: https://connect.ch.tudelft.nl
        - name: CONNECTCLIENTID
          value: mand
        - name: CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: mand
              key: OIDC_CLIENT_SECRET
        - name: REDIRECTURL
          value: https://wisv.ch/admin/
        - name: ALLOWEDGROUP
          value: mand
        - name: EMPTYREDIRECT
          value: https://ch.tudelft.nl/
        - name: NOTFOUNDURL
          value: https://ch.tudelft.nl/404
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 32Mi
