apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mand
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./default/mand
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system