apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: gke-ingress
    networking.gke.io/managed-certificates: managed-cert
spec:
  rules:
  - host: test.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: nginx-1-service
            port:
              number: 80
        pathType: ImplementationSpecific
  - host: test2.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        pathType: ImplementationSpecific
  - host: testmand.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: mand
            port:
              name: http
        pathType: ImplementationSpecific
  - host: register.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: member-registration
            port:
              name: http
        pathType: ImplementationSpecific
  - host: events.wisv.ch
    http:
      paths:
        - backend:
            service:
              name: events
              port:
                name: http
          pathType: ImplementationSpecific
