apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  rules:
  - host: test.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: nginx-1-service
            port:
              number: 80
        pathType: ImplementationSpecific
  - host: test2.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        pathType: ImplementationSpecific
