apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 34.149.67.180
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: test.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: nginx-1-service
            port:
              number: 80
        pathType: ImplementationSpecific
  - host: test2.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        pathType: ImplementationSpecific
  - host: testmand.wisv.ch
    http:
      paths:
      - backend:
          service:
            name: mand
            port:
              name: http
        pathType: ImplementationSpecific
