---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: events
  name: events
  namespace: default
spec:
  ports:
    - name: http 
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: events
  sessionAffinity: None
  type: ClusterIP
