apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: events
  namespace: flux-system
spec:
  image: ghcr.io/wisvch/events
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: events-repo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: events-image
  filterTags:
    pattern: '(?P<ts>[0-9]+)-.+'
    extract: $date
  policy:
    numerical:
      order: desc
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: events
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: events
  commit:
    authorEmail: julian9499@users.noreply.github.com
    authorName: julian9499
    messageTemplate: 'update image'
  interval: 1m0s
  update:
    strategy: Setters


#---
#apiVersion: image.toolkit.fluxcd.io/v1beta1
#kind: ImageRepository
#metadata:
#  name: events
#  namespace: flux-system
#spec:
#  image: ghcr.io/wisvch/events
#  interval: 1m0s
#  imageRepositoryRef:
#    name: events-image
#    filterTags:
#      pattern: '(?P<ts>[0-9]+)-.+'
#      extract: $date
#    policy:
#      numerical:
#        order: desc
#
#=======
#  image: ghcr.io/wisvch/events
#  interval: 1m0s
#---
#apiVersion: image.toolkit.fluxcd.io/v1beta1
#kind: ImagePolicy
#metadata:
#  name: events-repo-policy
#  namespace: flux-system
#spec:
#  imageRepositoryRef:
#    name: events-image
#  filterTags:
#    pattern: '(?P<ts>[0-9]+)-.+'
#    extract: $date
#  policy:
#    numerical:
#      order: desc
#>>>>>>> 8b05f9826966887e0882dc2fa9a612a0485aed71
