---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: events
  namespace: flux-system
spec:
  image: ghcr.io/wisvch/events
  interval: 1m0s
  imageRepositoryRef:
    name: events-image
  filterTags:
    pattern: '(?P<ts>[0-9]+)-.+'
    extract: $date
  policy:
    numerical:
      order: desc

