apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: anet-operator
  namespace: kube-system
spec:
  minAvailable: 0
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
